### PR TITLE
Change MOODLELIB to be owned by the moodle user

### PR DESCRIPTION
**Pull request by NeillM**
Moodle expects the MOODLELIB package to be owned by the
user that it connects to the database with. In this image it is
expected to be the moodle user.

Before this change the created MOODLELIB was ignored by
Moodle.

### CODE REVIEW

**Comment by stronk7** [comment]
I think NeillM is correct and the package should be owned by the moodle user, not sys (not good practice to create packages in that schema). Also, in fact, being owned by sys means that you need to create a public synonym and things like that. Not sure how it was working, to be honest.

Unless... it was working because moodle installation also tries to create the package if it's missing, and maybe that's what is happening. So the current sys package is never used and moodle installation creates (with the moodle user) the one used.

If that theory is correct, and moodle installation is already installing the package under the moodle schema... I'd say we don't need to do it as part of the image init at all.

So, I'd try with just 1 init script, creating the moodle user and adjusting everything else... and then let moodle install to create the package, really think that it should work that way (without needing to create the package from image setup).

**Comment by stronk7** [comment]
I've tried here only with `02-moodle-user.sql` init script (with the "moodlelib" grant line removed). And my built image ended with the package created on first connection with moodle user as owner as expected (noticeable because the 1st page spends a few secs before the install message is shown).

So I think that, as expected, we don't need to create the package as part of the image, just let moodle to do that automatically.

**Comment by scara** [comment]
TNX @stronk7 for your comments: I missed to check the Moodle code before commenting in https://github.com/moodlehq/moodle-docker/issues/34#issuecomment-327538941 (forgive my ignorance about Oracle 😊) i.e. https://github.com/moodle/moodle/blob/06e3b6d8bab42b8e56d169d006f31f4a15684830/lib/dml/oci_native_moodle_database.php#L1779.

Maybe https://github.com/moodle/moodle/blob/06e3b6d8bab42b8e56d169d006f31f4a15684830/lib/dml/oci_native_moodle_database.php#L204 could be a bit clearer and pointing to an area in the Wiki where these things above could be explained.

TIA,
Matteo

**Comment by danpoltawski** [comment]
> So I think that, as expected, we don't need to create the package as part of the image, just let moodle to do that automatically.

This was my intention when I first created this image.. but I obviously did something wrong and it wasn't working! Agree its much better not to bundle this package.

**Comment by danpoltawski** [comment]
> So I think that, as expected, we don't need to create the package as part of the image, just let moodle to do that automatically.

I have implemented this in 459ef68 (Sorry we didn't end up using this pull request @NeillM )

**Comment by NeillM** [comment]
No problems.

**Comment by stronk7** [comment]
Thanks all!

**Pull request closed without merging**
